service_account: default
users:
- name: making
  email: tmaki@vmware.com
  clusterroles:
  - app-editor
  - edit
- name: making-bot
  email: makingx+bot@gmail.com
  clusterroles:
  - app-editor
- name: imurata
  email: imurata@vmware.com
  clusterroles:
  - app-editor
  - edit
- name: gigiyy
  email: guixin.zhu@yahoo.com
  clusterroles:
  - app-editor
  - edit
- name: hirosat
  email: hirotaka0426@gmail.com
  clusterroles:
  - app-editor
  - edit
- name: boltKrank
  email: simon.anderson111@gmail.com
  clusterroles:
  - app-editor
  - edit
- name: kojiri
  email: kojiri@vmware.com
  clusterroles:
  - app-editor
  - edit
- name: balnbibarbi
  email: msanderson@vmware.com
  clusterroles:
  - app-editor
  - edit
