service_account: default
users:
- name: making
  email: tmaki@vmware.com
  clusterroles:
  - app-editor
  - edit
- name: making-bot
  email: makingx+bot@gmail.com
  clusterroles:
  - app-editor
- name: imurata
  email: imurata@vmware.com
  clusterroles:
  - app-editor
  - edit
