apiVersion: v1
kind: Secret
metadata:
  name: cnrs-default-tls
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-install-overlays"
type: Opaque
stringData:
  cnrs-default-tls.yml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@ namespace = data.values.ingress.external.namespace
    ---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: cnrs-default-tls
      namespace: #@ namespace
    spec:
      dnsNames:
      - #@ "*.{}".format(data.values.domain_name.replace("apps.", ""))
      - #@ "*.{}".format(data.values.domain_name)
      - #@ "*.{}".format(data.values.domain_name.replace("apps.", "sys."))
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt
      secretName: cnrs-default-tls
    ---
    apiVersion: projectcontour.io/v1
    kind: TLSCertificateDelegation
    metadata:
      name: contour-delegation
      namespace: #@ namespace
    spec:
      delegations:
      - secretName: cnrs-default-tls
        targetNamespaces:
        - "*"
    #@overlay/match by=overlay.subset({"metadata":{"name":"config-network"}, "kind": "ConfigMap"})
    ---
    data:
      #@overlay/match missing_ok=True
      default-external-scheme: https